<?php

namespace Database\Seeders;

use App\Models\Tour;
use Illuminate\Database\Seeder;

class TourSeeder extends Seeder
{
    public function run(): void
    {
        $tours = [
            // ---------------- KILIMANJARO ----------------
            [
                'category' => 'kilimanjaro',
                'title' => 'Lemosho Route',
                'slug' => 'lemosho-route',
                'summary' => 'The most scenic approach to the roof of Africa, with the highest summit success rate.',
                'description' => "The Lemosho Route is widely regarded as the most beautiful way up Kilimanjaro. Starting on the mountain's quieter western side, it crosses the Shira Plateau before joining the Northern Circuit for exceptional acclimatization. Eight days on the mountain gives your body time to adjust properly, which is why Lemosho consistently posts some of the highest summit success rates of any route.",
                'duration_days' => 8,
                'price_from' => 2450,
                'rating' => 4.9,
                'reviews_count' => 845,
                'difficulty' => 'Moderate',
                'group_size_max' => 12,
                'best_time' => 'June – October, late December – March',
                'highlight_stat' => '90% summit rate',
                'location' => 'Kilimanjaro National Park',
                'hero_image' => 'images/tours/lemosho.jpg',
                'gallery' => ['images/tours/lemosho-1.jpg', 'images/tours/lemosho-2.jpg', 'images/tours/lemosho-3.jpg'],
                'highlights' => [
                    'Highest summit success rate of any Kilimanjaro route',
                    'Crosses the remote Shira Plateau',
                    'Full extra acclimatization day at Barranco Camp',
                    'Sunrise summit at Uhuru Peak, 5,895m',
                ],
                'included' => ['Park fees and camping fees', 'Professional guides, cook and porters', 'All meals on the mountain', 'Mountain tents and eating tent', 'Emergency oxygen and first aid kit', 'Transfers to and from Kilimanjaro Airport'],
                'excluded' => ['International flights', 'Tanzania visa', 'Tips for guides and porters', 'Personal climbing gear'],
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'category' => 'kilimanjaro',
                'title' => 'Machame Route',
                'slug' => 'machame-route',
                'summary' => 'The "Whiskey Route" — a challenging, hugely rewarding climb through five distinct climate zones.',
                'description' => 'Known as the Whiskey Route for its reputation as one of the tougher paths up Kilimanjaro, Machame rewards climbers with dramatic scenery every single day — rainforest, moorland, alpine desert and glacier. Seven days on the mountain, camping throughout, with the iconic Barranco Wall scramble on day four.',
                'duration_days' => 7,
                'price_from' => 2150,
                'rating' => 4.8,
                'reviews_count' => 1930,
                'difficulty' => 'Challenging',
                'group_size_max' => 12,
                'best_time' => 'June – October, late December – March',
                'highlight_stat' => '85% summit rate',
                'location' => 'Kilimanjaro National Park',
                'hero_image' => 'images/tours/machame.jpg',
                'gallery' => ['images/tours/machame-1.jpg', 'images/tours/machame-2.jpg'],
                'highlights' => [
                    'Climbs through five ecological zones',
                    'The famous Barranco Wall scramble',
                    'Camping under the Southern Circuit stars',
                    'Panoramic views of the Western Breach',
                ],
                'included' => ['Park fees and camping fees', 'Professional guides, cook and porters', 'All meals on the mountain', 'Mountain tents and eating tent', 'Emergency oxygen and first aid kit', 'Transfers to and from Kilimanjaro Airport'],
                'excluded' => ['International flights', 'Tanzania visa', 'Tips for guides and porters', 'Personal climbing gear'],
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'category' => 'kilimanjaro',
                'title' => 'Marangu Route',
                'slug' => 'marangu-route',
                'summary' => 'The "Coca-Cola Route" — the only path with hut accommodation instead of tents.',
                'description' => "Marangu is the oldest and gentlest gradient on the mountain, and the only route with sleeping huts along the way instead of tents. Six days makes it the shortest standard option, which means a tighter acclimatization schedule — we always recommend adding a seventh day for a meaningfully better shot at the summit.",
                'duration_days' => 6,
                'price_from' => 1850,
                'rating' => 4.6,
                'reviews_count' => 530,
                'difficulty' => 'Moderate',
                'group_size_max' => 12,
                'best_time' => 'June – October, late December – March',
                'highlight_stat' => '65% summit rate',
                'location' => 'Kilimanjaro National Park',
                'hero_image' => 'images/tours/marangu.jpg',
                'gallery' => ['images/tours/marangu-1.jpg', 'images/tours/marangu-2.jpg'],
                'highlights' => [
                    'Sleeping huts instead of tents',
                    'Gentlest gradient of the standard routes',
                    'Shortest standard itinerary',
                    'Same descent path as ascent',
                ],
                'included' => ['Park fees and hut fees', 'Professional guides, cook and porters', 'All meals on the mountain', 'Emergency oxygen and first aid kit', 'Transfers to and from Kilimanjaro Airport'],
                'excluded' => ['International flights', 'Tanzania visa', 'Tips for guides and porters', 'Personal climbing gear'],
                'is_featured' => false,
                'sort_order' => 3,
            ],

            // ---------------- SAFARI ----------------
            [
                'category' => 'safari',
                'title' => 'Northern Circuit Explorer',
                'slug' => 'northern-circuit-explorer',
                'circuit' => 'northern',
                'summary' => 'Serengeti, Ngorongoro Crater and Tarangire in one seamless 6-day safari.',
                'description' => "Our signature safari covers Tanzania's classic Northern Circuit — the endless plains of the Serengeti, the wildlife-dense floor of the Ngorongoro Crater, and the baobab-studded landscapes of Tarangire. We build every itinerary around where the migration actually is that week, not a fixed template, so your route may shift a day or two to put you in the right place at the right time.",
                'duration_days' => 6,
                'price_from' => 2450,
                'rating' => 4.9,
                'reviews_count' => 2847,
                'difficulty' => 'Classic',
                'group_size_max' => 6,
                'best_time' => 'June – October, dry season',
                'highlight_stat' => '96% wildlife sightings',
                'location' => 'Serengeti, Ngorongoro & Tarangire',
                'hero_image' => 'images/tours/northern-circuit.jpg',
                'gallery' => ['images/tours/northern-circuit-1.jpg', 'images/tours/northern-circuit-2.jpg'],
                'highlights' => [
                    'Game drives tuned weekly to migration movement',
                    'Full day inside Ngorongoro Crater',
                    'Private 4x4 Land Cruiser with window seat for every guest',
                    'Tarangire\'s famous elephant herds and ancient baobabs',
                ],
                'included' => ['All park and conservation fees', 'Private 4x4 safari vehicle with pop-up roof', 'English-speaking driver-guide', 'Full board accommodation', 'Airport transfers'],
                'excluded' => ['International flights', 'Tanzania visa', 'Tips for guides', 'Alcoholic beverages'],
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'category' => 'safari',
                'title' => 'Southern Circuit Wilderness',
                'slug' => 'southern-circuit-wilderness',
                'circuit' => 'southern',
                'summary' => 'Ruaha and Nyerere National Park — vast, uncrowded wilderness far from the tourist trail.',
                'description' => "For travelers who want Tanzania's wildlife without the crowds, the Southern Circuit is the answer. Ruaha is one of Africa's largest national parks and one of its least visited, while Nyerere (formerly Selous) offers boat safaris along the Rufiji River alongside classic game drives. Expect long horizons, huge cat densities, and very few other vehicles.",
                'duration_days' => 7,
                'price_from' => 3100,
                'rating' => 4.8,
                'reviews_count' => 612,
                'difficulty' => 'Mid-range',
                'group_size_max' => 6,
                'best_time' => 'June – November',
                'highlight_stat' => 'Low-traffic parks',
                'location' => 'Ruaha & Nyerere National Parks',
                'hero_image' => 'images/tours/southern-circuit.jpg',
                'gallery' => ['images/tours/southern-circuit-1.jpg', 'images/tours/southern-circuit-2.jpg'],
                'highlights' => [
                    'One of Africa\'s highest lion and wild dog densities',
                    'Boat safari on the Rufiji River in Nyerere',
                    'A fraction of the vehicle traffic of the Northern Circuit',
                    'Fly-in options available to save travel time',
                ],
                'included' => ['All park and conservation fees', 'Private 4x4 safari vehicle', 'English-speaking driver-guide', 'Full board accommodation', 'Boat safari activity fees'],
                'excluded' => ['International flights', 'Domestic flights (unless specified)', 'Tanzania visa', 'Tips for guides'],
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'category' => 'safari',
                'title' => 'Tarangire & Lake Manyara Short Break',
                'slug' => 'tarangire-lake-manyara-short-break',
                'circuit' => 'northern',
                'summary' => 'A compact 4-day safari for travelers short on time but not on ambition.',
                'description' => "Don't have two weeks to spare? This four-day loop pairs Tarangire's elephant herds and towering baobabs with Lake Manyara's tree-climbing lions and flamingo-lined shores — a genuine Big Five taste of Tanzania that fits neatly before or after a Zanzibar beach stay.",
                'duration_days' => 4,
                'price_from' => 1200,
                'rating' => 4.7,
                'reviews_count' => 398,
                'difficulty' => 'Budget',
                'group_size_max' => 6,
                'best_time' => 'Year-round',
                'highlight_stat' => 'Quick 4-day escape',
                'location' => 'Tarangire & Lake Manyara National Parks',
                'hero_image' => 'images/tours/tarangire-manyara.jpg',
                'gallery' => ['images/tours/tarangire-manyara-1.jpg'],
                'highlights' => [
                    'Some of Africa\'s largest elephant herds',
                    'Tree-climbing lions in Lake Manyara',
                    'Easy add-on before or after Zanzibar',
                    'Comfortable lodge or tented camp accommodation',
                ],
                'included' => ['All park and conservation fees', 'Private 4x4 safari vehicle', 'English-speaking driver-guide', 'Full board accommodation'],
                'excluded' => ['International flights', 'Tanzania visa', 'Tips for guides', 'Alcoholic beverages'],
                'is_featured' => false,
                'sort_order' => 3,
            ],

            // ---------------- ZANZIBAR ----------------
            [
                'category' => 'zanzibar',
                'title' => 'Zanzibar Beach Escape',
                'slug' => 'zanzibar-beach-escape',
                'summary' => 'White-sand beaches and turquoise water on the Spice Island — the perfect safari finale.',
                'description' => "After days of dust and early-morning game drives, Zanzibar is the reset. This escape settles you into a beachfront stay on the island's northeast coast, with warm, calm water for swimming and snorkeling and the kind of sunsets people build entire trips around. Add a Stone Town and spice farm day if you want a little culture with your relaxation.",
                'duration_days' => 4,
                'price_from' => 890,
                'rating' => 4.9,
                'reviews_count' => 1520,
                'difficulty' => 'Relaxed',
                'group_size_max' => 8,
                'best_time' => 'June – October',
                'highlight_stat' => 'Free cancellation 48h',
                'location' => 'Zanzibar Archipelago',
                'hero_image' => 'images/tours/zanzibar-beach.jpg',
                'gallery' => ['images/tours/zanzibar-beach-1.jpg', 'images/tours/zanzibar-beach-2.jpg'],
                'highlights' => [
                    'Beachfront accommodation on the northeast coast',
                    'Snorkeling over Zanzibar\'s coral reefs',
                    'Optional sunset dhow cruise',
                    'Seamless add-on to any safari or Kilimanjaro trip',
                ],
                'included' => ['Beachfront accommodation with breakfast', 'Airport and ferry transfers', 'One snorkeling excursion'],
                'excluded' => ['International flights', 'Tanzania visa', 'Lunches and dinners', 'Optional excursions'],
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'category' => 'zanzibar',
                'title' => 'Stone Town & Spice Farm Cultural Tour',
                'slug' => 'stone-town-spice-farm-cultural-tour',
                'summary' => 'A half-day journey through Zanzibar\'s history, architecture, and fragrant spice plantations.',
                'description' => 'Wander the narrow coral-stone alleys of Stone Town, a UNESCO World Heritage Site shaped by Swahili, Arab, Persian and Indian influence, then head inland to a working spice farm to see — and taste — the cloves, vanilla, cinnamon and nutmeg that once made this island one of the most fought-over ports in the Indian Ocean.',
                'duration_days' => 1,
                'price_from' => 95,
                'rating' => 4.8,
                'reviews_count' => 398,
                'difficulty' => 'Cultural',
                'group_size_max' => 10,
                'best_time' => 'Year-round',
                'highlight_stat' => 'Half-day tour',
                'location' => 'Stone Town, Zanzibar',
                'hero_image' => 'images/tours/stone-town.jpg',
                'gallery' => ['images/tours/stone-town-1.jpg'],
                'highlights' => [
                    'Guided walk through UNESCO-listed Stone Town',
                    'Working spice farm tasting tour',
                    'Local lunch included',
                    'Can be combined with any beach stay',
                ],
                'included' => ['Local guide', 'Spice farm entrance and tasting', 'Lunch', 'Hotel transfers'],
                'excluded' => ['International flights', 'Tanzania visa', 'Personal purchases'],
                'is_featured' => false,
                'sort_order' => 2,
            ],
        ];

        foreach ($tours as $tour) {
            Tour::updateOrCreate(['slug' => $tour['slug']], $tour);
        }
    }
}
